language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.2

cache:
  directories:
    - deps

notifications:
  email:
    on_success: never
    on_failure: always

script: mix test && MIX_ENV=test mix coveralls.travis
