language: elixir
elixir:
  - 1.4.0
otp_release:
  - 19.2

cache:
  directories:
    - deps

notifications:
  email:
    on_success: never
    on_failure: always

env:
  - MIX_ENV=test

script: mix coveralls.travis
